---
title: "Personal Knowledge Management — What, Why and How?"
author: "Hui Lin"
date: "April 9, 2016"
output: html_document
---

> Organised common (or uncommon) sense – very basic knowledge is an enormously powerful tool... You have to have a temperament to grab ideas and do sensible things. [Charlie Munger]

# What is PKM?

It is better to ask [Wikipedia](https://en.wikipedia.org/wiki/Personal_knowledge_management). Here is what I got:

> Personal knowledge management (PKM) is a collection of processes that a person uses to gather, classify, store, search, retrieve, and share knowledge in his or her daily activities and the way in which these processes support work activities. It is a response to the idea that knowledge workers increasingly need to be responsible for their own growth and learning. [Wikipedia]


Personal Knowledge Management (PKM) need time to develop and I told myself to be patient. It talks me very long time to realize I badly need PKM. I love books which has been the case since I can remember. However, I was not on purposely selective about what I read. Being a random reader, I went to a bookstore, randomly picked book and read whatever seemed to interest me at that time.  Or sometimes my friends recommended book to me. It seems to be the attitude towards many other things: choose from whatever come to me that seemed interest me instead of **knowing what I want and go to get it**. 


芒格的话：
德鲁克：没有人为你负责，除了你自己，而你唯一的资本就是知识。

知识管理是一个需要时间培养的过程，

给我选择筛选书籍的能力。我非常喜欢看书，开始的时候
