---
title: "书评：《白痴》陀思妥耶夫斯基"
output: html_document
layout: post
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

《白痴》是一部近600字的长篇小说，描绘了一个纯洁男主——梅诗金公爵，他被很多人视为白痴，因为长期在国外疗养，回国后和周围的生活脱节，显得不谙世故，但他有着一颗水晶般纯净无邪的仁爱之心，光明磊落，任何权术城府和他都是不沾边的。在一个由伪善虚假编织成的罗网里，一旦有人捅破那层薄薄的遮掩，这妖魔化的世界便不成体统。一切都是颠倒的：善良成了白痴，仁爱变成无用。而最终梅诗金公爵也没能撼动这张根深蒂固的网。

在回俄国的火车上，他遇到了罗果仁，一个痴迷于美丽的娜斯塔霞的富二代。娜斯塔霞，各种小说戏剧影视中描述的红颜薄命的女子中的一员，并没有给我留下深刻的印象。她美貌、聪慧、出生悲惨，处于阴谋的中心但不甘心受人摆布，敢于在富豪权贵头上动土，最后香消玉损，这样的形象仿佛是嚼了几个世纪的口香糖，无感。反倒是罗果仁，因为其内心的阴暗和对娜斯塔霞病态的迷恋最终导将他们三个人都拖入悲惨的结局，这样一个邪恶而愚蠢的人格，让人印象深刻。

陀氏笔下的梅诗金公爵反映了作者本人对“完完全全美好的人”的定义，他认为真正美好的人物在这个尘世必定是可笑的，美好者不知自身价值，反而遭到嘲笑，于是引起同情，也衬托的真实社会的丑恶。作者对公爵的性格描绘显然受到了圣经福音书的影响，圣徒一样的公爵在社会上饱受欺侮，可是他不愤怒，不反抗，总是逆来顺受，还时不时为自己“以小人之心度君子之腹”而自责，和周着世界形成触目惊心的对比。此外，在某层面上白痴这本书本身就有一种基督降临的寓言的味道——完美的梅诗金公爵带着某种高尚的使命从瑞士疗养院来到彼得堡这样一个充满人性罪恶的鱼龙混杂之地，他用自身的爱和宽容感化拯救周围的人。

小说中的每个形象通常代表了那个时代的某一种观点。作者对人物性格的描绘方式有些“不着一字，褒贬风流”的感觉。陀并没有用花很多笔墨去直接描述人物性格，而是用实时记录言行的方式，好像有架摄像机，实时的在暗拍，观察他们都在说什么，做什么。作者带领我们在这些人的交谈行为之间穿梭，由读者自己去理解背后的潜台词：

- 梅诗金公爵：纯洁，高尚，富有同情心，体谅一切人间疾苦因此显得和社会格格不入
- 罗果仁：杀气腾腾，他的存在仿佛恶之花的绽放，因为梅诗金公爵对他的宽恕和容忍与其本身的恶形成对比，反而更加憎恨公爵。
- 娜斯塔霞：美丽，轻浮，内心深处却又善良。
- 叶班钦将军：成功又是传统的家庭型男人，白开水一样的人，平淡，寡味，但适合过日子。有作死到不行的老婆和女儿，他这样的性格对家庭的维系至关重要
- 安格拉雅：将军的最小的女儿，美貌幼稚，对家人的期待有很强的叛逆心理，典型的不作死就不会死的角色，一会绿茶婊，一会圣母婊，关于安格拉雅的部分是我最想跳过的，但因为其何主人公关系密切，又跳不过
- 加尼亚：想要金钱又想要爱情，但却悲剧性的面临无法两全的境地，最后将一切矛头指向他那个死要面子，不切实际的父亲——伊沃尔金
- 伊沃尔金：加尼亚的父亲，一个自私病态的角色，沉浸在昔日的辉煌中无法自拔，逢人便夸夸其谈讲述许多臆想出来的往日辉煌，除了关心自己外对家庭没有丝毫责任感
- 列别杰夫：谄媚者，溜须拍马人格，毫无道德感可言，也是一个具有病态的丑恶角色。

读完全书可以感觉到，陀将孩子看成美好灵魂的载体，这一孩子气的纯真是成年人失去的。书中为数不多的几个正面形象中，有两个都是孩子：加尼亚的弟弟郭力亚，一个忠实，正直的男孩；薇拉（列别杰夫的女儿）和她的父亲截然不同，她富有同情心，温柔的甚至有些软弱。至于公爵本身，也是和孩子一般，天真、诚实，极其容易信任周围的人，即使受到伤害也很容易就宽恕对方。即使是个成年人，但他保存了很多孩子的特质。我觉得这一点和娜斯塔霞的红颜薄命一样，有点陈词滥调。

掩卷而思，这样一本近600页的小说除了是一个悲剧性的故事之外还有什么？小说中有一幅画多次出现，是书中角色罗果仁家的一副临摹霍尔拜因（Hans Holbein）在1521年创作的《基督在棺中(The Body of the Dead Christ in the Tomb)》，陀曾经在巴塞尔看过这幅画，留下极深的印象。这幅作品画的是刚刚从十字架上被取下来的基督那扭曲，折磨致死的尸体，其表明了一个神圣的灵魂在罪恶的人世间无法存在。这就是作者设计一个悲剧性结果的寓意么？我觉得不是这样的。因为作者同样描述了书中那些芸芸众生各种“矛盾”的心理，让人感觉到即使再卑鄙的人，也不全是恶的，时不时脑子里也还存有一丝善念，也会偶尔真心忏悔。我想陀希望突出的不仅仅是像公爵这样悲剧性富有同情心的高尚角色，对于那些灵魂堕落的角色，作者也时不时解开帘幕一角，稍纵即逝一瞥这些自私虚伪嘴脸背后善犹存的爱、友情、同情甚至是自尊。在人类种种行为背后有某种救赎的力量给人以希望，我觉得陀思妥耶夫斯基最根处还是乐观的。

总结起来，这本书读下来我的脑中有这样一些关键词：无神论与基督教；虚无主义与垂死的社会秩序；真实和虚伪；本我、自我和超我（弗洛伊德精神分析学说中的三个概念）。阅读这本书有感觉迷人的时候，也有不耐烦的时候，但不管怎样，在这样碎片化的时代，系统的读完这样一本并不让人轻松的小说，花时间去思考作者背后想要传达的思想以及如何通过笔下的各种人物将他的思想传达出来，这个过程本身感觉像是一种思维试验，个人觉得对碎片化阅读给我们造成的负面影响有中和作用。