---
title: "Autobiography In Five Short Chapters"
output: html_document
layout: post
---

I first read the poem “Autobiography in Five Short Chapters
" by Portia Nelson in 2015. Sogyal Rinpoche adopted the poem in his book “The Tibetan Book of Living and Dying”. Several days ago, I read the poem again in an article. It describes the growth process of many.  It is difficult and effortful to grow because we have the natural inclination to keep things the way they were, to cling to the old maps and old ways of doing things even after we fall. La Rochefoucauld says: “We have more idleness in the mind than in the body.”  Portia Nelson was lucky to have the whole five chapters in her life. Unfortunately, many people simply repeat the first two chapters all their lives. But there are people do grow. What is the force that push those people to change, to walk down another street? It is love. 


<blockquote>  Love was defined as “the will to extend one’s self for the purpose of nurturing one’s own or another’s spiritual growth”. When we grow, it is because we are working at it, and we are working at it because we love ourselves. It is through love that we elevate ourselves. And it is through our love for others that we assist others to elevate themselves. Love, the extension of the self, is the very act of evolution. It is evolution in progress. The exclusionary force, present in all of life, manifest itself in mankind as human love. Among humanity love is the miraculous force that defies the natural law of entropy.
----- From "The Road Less Travelled" [M Scott Peck]
</blockquote>

According to the second law of thermodynamics, in billions and billions of years, the universe will completely wind down until it reaches the lowest point as amorphous, totally disorganized, totally undifferentiated “blob” in which nothing happens any more. Our human body follows this law. It is inevitable that we will decline physically as we getting older. But the spirit may evolve. Even we are not growing alone a straight line but spiral. The important thing is we do grow if we want to. Go through the whole five chapters and don’t stop at chapter two…...


<blockquote>

 <p> Autobiography In Five Short Chapters </p>

<p> By  Portia Nelson </p>

<p> Chapter I </p>

<p> I walk down the street.  </p>
<p>There is a deep hole in the sidewalk. </p> 
<p>I fall in.  </p>
<p>I am lost... I am hopeless.  </p>
<p>It isn't my fault.  </p>
<p>It takes forever to find a way out.   </p> 

<p>Chapter II</p>

<p>I walk down the same street.  </p>
<p>There is a deep hole in the sidewalk.  </p>
<p>I pretend I don't see it.  </p>
<p>I fall in again.  </p>
<p>I can't believe I am in this same place.  </p>
<p>But it isn't my fault.  </p>
<p>It still takes a long time to get out.  </p>

<p>Chapter III</p>

<p>I walk down the same street.  </p>
<p>There is a deep hole in the sidewalk.  </p>
<p>I see it there.  </p>
<p>I still fall in... it's a habit... but, </p> 
<p>my eyes are open.  </p>
<p>I know where I am. </p> 
<p>It is my fault.  </p>
<p>I get out immediately.  </p>

<p>Chapter IV  </p>

<p>I walk down the same street.  </p>
<p>There is a deep hole in the sidewalk.  </p>
<p>I walk around it.  </p>

<p> Chapter V  </p>

<p>I walk down another street.  </p>
</blockquote>
